recipe: default.v1
language: en
pipeline:
- name: "vietnamese_tokenizer.VietnameseTokenizer"
- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: bert-base-uncased
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
- name: EntitySynonymMapper
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true

assistant_id: 20231012-013437-savage-object
