recipe: default.v1
language: vi
pipeline:
- name: "vietnamese_tokenizer.VietnameseTokenizer"
- name: LexicalSyntacticFeaturizer
  intent_split_symbol: "+"
  intent_tokenization_flag: true

- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

- name: DIETClassifier
  random_seed: 42
  intent_classification: true
  entity_recognition: true
  epochs: 300
  learning_rate: 0.002
  embedding_dimension: 60
  number_of_transformer_layers: 1
  batch_size: 64
  hidden_layer_sizes: null
  text: [256, 128]

# - name: transformer_classifier.TransformerClassifier
#   model_name: "albert-base-v2"
#   epochs: 100
#   batch_size: 32
#   learning_rate: 0.00002
#   warmup_steps: 500
#   weight_decay: 0.01
#   scheduler_type: "constant"
#   max_length: 64

- name: ResponseSelector
  epochs: 800
  retrieval_intent: faq
- name: EntitySynonymMapper

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true

assistant_id: 20240320-204246-randomized-strategy
