recipe: default.v1
language: vi
pipeline:
- name: "vietnamese_tokenizer.VietnameseTokenizer"
- name: LexicalSyntacticFeaturizer
  
  intent_tokenization_flag: true
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

- name: DIETClassifier
  random_seed: 42
  intent_classification: True
  entity_recognition: True
  epochs: 200
  learning_rate: 0.002
  embedding_dimension: 60
  number_of_transformer_layers: 1
  batch_size: 64
  hidden_layer_sizes:
  text: [256, 128]

# - name: CRFEntityExtractor
#   BILOU_flag: True

- name: ResponseSelector
  epochs: 800
  retrieval_intent: faq
- name: EntitySynonymMapper
# - name: FallbackClassifier
#   threshold: 0.3

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true

assistant_id: 20231019-082525-isochoric-altitude