version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: genius_db
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD=yes
      MYSQL_DATABASE: genius_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: