recipe: default.v1
language: vi
pipeline:
  - name: "vietnamese_tokenizer.VietnameseTokenizer"

  - name: LexicalSyntacticFeaturizer
    intent_split_symbol: "+"
    intent_tokenization_flag: true
  - name: LanguageModelFeaturizer
    # Name of the language model to use
    model_name: "bert"
    # Pre-Trained weights to be loaded
    model_weights: "rasa/LaBSE"

    cache_dir: null
  # - name: CountVectorsFeaturizer
  # - name: CountVectorsFeaturizer
  #   analyzer: char_wb
  #   min_ngram: 1
  #   max_ngram: 4
  - name: "SklearnIntentClassifier"

    C: [1, 2, 5, 10, 20, 100]
    # Specifies the kernel to use with C-SVM.
    # This is used with the ``C`` hyperparameter in GridSearchCV.
    kernels: ["linear"]
    # Gamma parameter of the C-SVM.
    "gamma": [0.1]
    # We try to find a good number of cross folds to use during
    # intent training, this specifies the max number of folds.
    "max_cross_validation_folds": 5
    # Scoring function used for evaluating the hyper parameters.
    # This can be a name or a function.
    "scoring_function": "f1_weighted"
    # - name: transformer_classifier.TransformerClassifier

  #   model_name: "albert-base-v2"
  #   epochs: 100
  #   batch_size: 32
  #   learning_rate: 0.00002
  #   warmup_steps: 500
  #   weight_decay: 0.01
  #   scheduler_type: "constant"
  #   max_length: 64

# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true

assistant_id: 20230923-231551-proper-basis